### PR TITLE
[Invalid]

### PR DESCRIPTION
**Pull request by winstonsung**

### CODE REVIEW

**Comment by rutopio** [comment]
字符 in here means 'glyph', rather than 'character'.

A 'character', the symbol representing a letter, can be represented by many 'glyphs' set. Designers can design a few of glyphs with different style for one charater. Contextual alternates (calt) feature in Opentype is to replaces default 'glyphs' with alternate forms. [^1]

[^1]: https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae

**Comment by winstonsung** [comment]
"glyph" should be "字形" afaik?

**Comment by rutopio** [comment]
Please refer to [National Academy for Educational Research (NAER)](http://terms.naer.edu.tw/search/?csrfmiddlewaretoken=qYQSnuGwiCunalaO1bJ9k44Xt72PARJlYM4XgoWn27kT7dB8j2DN3GAVSZ5cafpI&match_type=phrase&query_op=&query_field=title&query_term=glyph&filter_term=&filter_field=&filter_op=&filter_bool=&filter_term=&filter_field=&filter_op=&filter_bool=&filter_term=&filter_field=&filter_op=&filter_bool=&filter_term=&filter_field=&filter_op=&filter_bool=).

**Comment by winstonsung** [comment]
Oh, nvm, fond it.

Thanks for the information.

> character form 字形

**Pull request closed without merging**
